### ISSUE TITLE
Kicked out of my account after using and i cant login back

### ISSUE THREAD

**Issue by artificer1** [sockysec/Telerecon#27]
I tried to scrape info from channel (2 option) and it crashed, then i opened my telegram tab and i got locked out

**Comment by sockysec** [comment]
Hey, would you mind elaborating on which specific script you used? Option 2 dosn't appear to align with what you are describing. 

It's most likely that:
- You hit some sort of API rate limit due to the size of the channel (this could be avoided in the future by increasing the request_delay on the script)
- You were locked out for some issue unrelated to Telerecon (i.e. breaching T&C's / IP being blacklisted etc)

This issue is highly anomalous and almost always related to the user's own environment/use.

**Comment by artificer1** [comment]
Okay, there were a mistake, i used option 10 (as i remember) and i got locked out, i think there is some steps to reproduce:
1) Run Telegram on your PC which is running a NL vpn and setup telerecon
2) Test telerecon with options (just goofed around, might work)
3) Use that one specific option (10)
4) Get locked out. 
It just feels like i got locked out because of rate limit (telegram servers think i got hacked)
Im closing that issue because i got my account back

**Comment by sockysec** [comment]
Glad you managed to get your account back! 

Thanks for the additional details - interestingly, Option 10 runs locally across collected data and dosn't interface with Telegrams API, so it is highly unlikely/impossible that it caused the rate limit/ban on your account.

I highly suspect it was due to your VPN connection (maybe in association with one of the other options?) - if Telegram has previously seen abuse/account breaches from a particular IP (i.e. a free VPN connection), they are likely more sensitive surrounding rate limits/banning etc.
